### ISSUE TITLE
Set icon for OpenFloodAI App

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#1]
Set icon for OpenFloodAI App 
here is the icon 
![OpenFloodAI-min](https://user-images.githubusercontent.com/31799654/65898101-6f34a500-e3ce-11e9-8946-dad33695f064.png)

**Comment by ngwutadesmond** [comment]
can I take this up? and do you mean "set a launcher Icon"?

**Comment by ghost** [comment]
Sure, @chydee go ahead! I have assigned you

**Comment by ngwutadesmond** [comment]
Okay, I already added the ICON
