### ISSUE TITLE
Set icon for OpenFloodAI App icon

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#12]
Set icon for OpenFloodAI App Icon
[App icon](https://user-images.githubusercontent.com/31799654/65898101-6f34a500-e3ce-11e9-8946-dad33695f064.png)

**Comment by deepakumarvu** [comment]
I would like to take it

**Comment by ghost** [comment]
sure @syk007
 maybe find the bug and make sure the app icon is visible after installing the app in an android device! share a screenshot for that if possible!

**Comment by deepakumarvu** [comment]
okay will post it

**Comment by deepaksinghcv** [comment]
Is this active?
I would like to take this issue.

**Comment by ghost** [comment]
> maybe find the bug and make sure the app icon is visible after installing the app in an android device! share a screenshot for that if possible!

Yes @deepakksingh You can go ahead :)
