### ISSUE TITLE
add screenshots or gifs for OpenFloodAI APP on README

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#14]

**Comment by werainkhatri** [comment]
there are only 2 screens in the app. so just two images? Or just a gif for the transition between the two?

**Comment by ghost** [comment]
Hi, @werainkhatri! a gif transition with visiting any OpenFloodAI social handle will be fine 👍

**Comment by werainkhatri** [comment]
#16

**Comment by werainkhatri** [comment]
#16

**Comment by werainkhatri** [comment]
#15 [Updating ReadME](https://github.com/OpenFloodAI/OpenFloodAI-Android/pull/16)

**Comment by werainkhatri** [comment]
> Hi, @werainkhatri! a gif transition with visiting any OpenFloodAI social handle will be fine +1

#16 Updated ReadME file
