### ISSUE TITLE
add OpenFloodAI dev.to link to app

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#18]
add OpenFloodAI dev.to link with the icon to app 
https://dev.to/openfloodai
also reorder the social button as

**Twitter Facebook Linkedin Dev.to GitHub**

**Comment by goninty** [comment]
Hiya, I can take this one.

**Comment by goninty** [comment]
Hey, I've made the pull request, it can be found at #19
