### ISSUE TITLE
write a CONTRIBUTING.md for OpenFloodAI-Android

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#21]
here is the [CONTRIBUTING.md](https://github.com/OpenFloodAI/OpenFloodAI-Android/blob/master/CONTRIBUTING.md) file

**Comment by HemanshuVarma** [comment]
Can you elaborate this what exactly to be done. So that I can work on it.

**Comment by ghost** [comment]
Hi @HemanshuVarma! 
here are two examples

 [CONTRIBUTING.md](https://github.com/OpenFloodAI/OpenFloodAI/blob/master/CONTRIBUTING.md)
[CONTRIBUTING.md](https://github.com/OpenFloodAI/openfloodai.github.io/blob/master/CONTRIBUTING.md)

**Comment by HemanshuVarma** [comment]
Thanks! I'd be working on this. :)
