### ISSUE TITLE
add dark theme for the OpenFlood App

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#3]
add **dark theme** feature for the OpenFlood App 

// add a button on the upper right corner for dark theme (choose a related icon for it!)
// when the button is pressed the app theme changes to dark

**Comment by Piyush7890** [comment]
I would like to work on this issue.

**Comment by Piyush7890** [comment]
I would like to work on this issue.

**Comment by ghost** [comment]
Sure, @Piyush7890! I have assigned you
