### ISSUE TITLE
Write a simple README for OpenFloodAI App

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#4]
Write a simple README for OpenFloodAI App

**Comment by SankalpSh** [comment]
@adventuroussrv I  would like to work on this.

**Comment by SidneyMachara** [comment]
can you please provide more information about the App

**Comment by ghost** [comment]
Sure! @SankalpSh I have assigned you

**Comment by ghost** [comment]
> can you please provide more information about the App

Hi @SidneyMachara!
The App is simple! We are just opening simple features to it for now,
Later we might use it for model deployment!
