### ISSUE TITLE
Add a business card design on Home Screen of the OpenFloodAI App

### ISSUE THREAD

**Issue by ghost** [OpenFloodAI/OpenFloodAI-Android#7]
# **Add a Business card design on Home Screen of the OpenFloodAI  App**

## Add Social Icons
when the icon is clicked it opens the link!
//When the twitter icon is clicked it opens the OpenFloodAI twitter handle

**OpenFloodAI**
OpenFloodAI is an open-source community dedicated & focused on research & developing solutions for Flood related issues.

Twitter: https://twitter.com/OpenFloodAI
Facebook: https://www.facebook.com/OpenFloodAI
Linkedin: https://www.linkedin.com/company/openfloodai
Github: https://github.com/OpenFloodAI

**Comment by Piyush7890** [comment]
can i take this issue?

**Comment by ghost** [comment]
HI @Piyush7890 Sure, Go ahead!

**Comment by Piyush7890** [comment]
This is what it looks like
![Screenshot_20191004-210902](https://user-images.githubusercontent.com/25117135/66220988-b16e2700-e6eb-11e9-8277-fc5a242478fa.jpeg)
![Screenshot_20191004-210907](https://user-images.githubusercontent.com/25117135/66220989-b337ea80-e6eb-11e9-9550-d365dd83bec6.jpeg)

**Comment by ghost** [comment]
Awesome @Piyush7890! You may make a PR
